### ISSUE TITLE
Errors in README.md examples

### ISSUE THREAD

**Issue by AndyClifton** [chgrl/bReeze#4]
The current readme includes the following suggested commands:

```r
# calculate wind profile
pf <- windprofile(mast=metmast, v.set=c(1,2), dir.set=1)

# import power curve
pc <- pc("Enercon_E126_7.5MW.pow")

# calculate annual energy production
aep <- aep(profile=pf, pc=pc, hub.h=135)

# plot AEP
plot(aep)
```

There are a few problems with this:
   1. the `windprofile()` function doesn't work. However, the alias `pro()` works, and the function `profile()` also works.
   2. the `aep()` function doesn't work. I get this error: 

```r
> aep <- aep(profile=pf, pc=pc, hub.h=135)
Error in mast$timestamp : object of type 'closure' is not subsettable
```

**Comment by chgrl** [comment]
I guess at least the release CRAN version 0.4-3 solved this.
